# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 22:50
from __future__ import unicode_literals

import captura.models
import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizacion', models.DateField(blank=True, null=True)),
                ('inicio_actualizacion', models.DateField(blank=True, null=True)),
                ('subida', models.DateTimeField(auto_now_add=True, null=True)),
                ('validacion', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=captura.models.user_directory_path)),
                ('anio', models.IntegerField(default=2019)),
                ('trimestre', models.IntegerField(default=0)),
                ('html', tinymce.models.HTMLField(default='')),
            ],
            options={
                'ordering': ('-subida',),
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024)),
                ('titulo', models.CharField(default='Marco legal aplicable', max_length=1024)),
                ('descripcion', tinymce.models.HTMLField()),
                ('orden', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fracciones', to='captura.Articulo')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('descripcion', tinymce.models.HTMLField()),
                ('color', colorful.fields.RGBColorField(null=True)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelGobierno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('color', colorful.fields.RGBColorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('color', colorful.fields.RGBColorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('unidad_administrativa', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024)),
                ('descripcion', tinymce.models.HTMLField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='ls/%Y/%m/%d')),
                ('subida', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.CharField(default='0000-00000-000000-000000', max_length=254)),
                ('html', tinymce.models.HTMLField(default='')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-subida',),
            },
        ),
        migrations.AddField(
            model_name='ley',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captura.NivelGobierno'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ley',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='captura.Ley'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Responsable'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='captura.Articulo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Responsable'),
        ),
    ]
